Repository storyofams/react-ui, pull requests merged in 2021-03, with the labels that each got.

#10 feat: modal
  package.json
  src/components/common/Icon/library/close.svg
  src/components/common/Icon/library/index.ts
  src/components/common/Modal/index.tsx
  src/components/common/Modal/modal.stories.tsx
  src/components/common/Modal/modal.test.tsx
  src/components/index.ts
  yarn.lock
Labels: Priority: Medium, Type: Feature

#12 codecov
  .github/workflows/test.yaml
Labels: Priority: Medium, Status: Review Needed, Type: CI, Type: Feature, Type: Testing

#16 docs: 📝 updated readme content
  README.md
  example/src/styles/styled.d.ts
  package.json
Labels: Priority: Medium, Status: In Progress, Type: Documentation

#18 fix(button): 🐛 small changes to prop name + propforwarding
  src/components/common/Box/box.test.tsx
  src/components/common/Box/index.tsx
  src/components/common/Button/index.tsx
Labels: Priority: Medium, Type: Refactoring

#24 refactor: system-props
  package.json
  src/components/common/Accordion/index.tsx
  src/components/common/Box/box.stories.tsx
  src/components/common/Box/index.tsx
  src/components/common/Breadcrumb/index.tsx
  src/components/common/Button/button.stories.tsx
  src/components/common/Button/button.test.tsx
  src/components/common/Button/index.tsx
  src/components/common/DatePicker/index.tsx
  src/components/common/Flex/index.tsx
  src/components/common/Grid/index.tsx
  src/components/common/Heading/index.tsx
  src/components/common/Icon/index.tsx
  src/components/common/Input/index.tsx
  src/components/common/InputWrapper/index.tsx
  src/components/common/Modal/index.tsx
  src/components/common/Spinner/index.tsx
  src/components/common/Stack/index.tsx
  src/components/common/StatusMessage/index.tsx
  src/components/common/Text/index.tsx
  src/components/common/Textarea/index.tsx
  src/index.ts
  src/lib/system.ts
  src/types/styled.ts
  src/types/system.ts
  yarn.lock
Labels: Priority: Medium, Status: Review Needed, Type: Refactoring
